# Generated by Django 6.0 on 2025-12-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unit_number', models.CharField(max_length=20)),
                ('shop_bench', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('category_of_business', models.CharField(choices=[('hardware', 'Hardware'), ('food', 'Food'), ('stationery', 'Stationery'), ('textile', 'Textile'), ('barbershop', 'Barbershop/Salon'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=30)),
                ('tpin', models.CharField(blank=True, max_length=15, null=True)),
                ('membership_of_association', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nations',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by_full_name', models.CharField(max_length=100)),
                ('approved_by_organisation', models.CharField(max_length=100)),
                ('approval_date', models.DateField()),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('business_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='vendormis.businessdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_by_full_name', models.CharField(max_length=100)),
                ('collected_by_organisation', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('collection_date', models.DateField()),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_collection', to='vendormis.approval')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('market_code', models.CharField(max_length=20, null=True, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='vendormis.district')),
            ],
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='vendormis.market'),
        ),
        migrations.AddField(
            model_name='district',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.nation'),
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('national_id_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendormis.nation')),
            ],
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='personal_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='vendormis.personaldetail'),
        ),
        migrations.CreateModel(
            name='TraditionalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.district')),
            ],
            options={
                'verbose_name_plural': 'Traditional Authorities',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('traditional_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.traditionalauthority')),
            ],
            options={
                'verbose_name_plural': 'Villages',
            },
        ),
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.district')),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_addresses', to='vendormis.personaldetail')),
                ('traditional_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.traditionalauthority')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.village')),
            ],
            options={
                'verbose_name_plural': 'Residential Addresses',
            },
        ),
        migrations.CreateModel(
            name='DistrictOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.district')),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_of_origin', to='vendormis.personaldetail')),
                ('traditional_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.traditionalauthority')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.village')),
            ],
        ),
    ]
