# Generated by Django 5.2.5 on 2026-05-03 15:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendormis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +265999123456).', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
