# Generated by Django 5.2.5 on 2026-05-04 07:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendormis', '0003_loginactivity'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentialaddress',
            options={},
        ),
        migrations.AlterField(
            model_name='approval',
            name='business_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendormis.businessdetail'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendormis.market'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='personal_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='vendormis.personaldetail'),
        ),
        migrations.AlterField(
            model_name='districtoforigin',
            name='personal_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.personaldetail'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendormis.approval'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='market',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.district'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid Malawi number e.g. +265991234567', regex='^\\+?265?\\d{8,12}$')]),
        ),
        migrations.AlterField(
            model_name='residentialaddress',
            name='personal_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormis.personaldetail'),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('vendor_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendormis.personaldetail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
