# Generated by Django 6.0 on 2025-12-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_staffmember_ourstaffpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='International format e.g. +265999000000', max_length=20),
        ),
    ]
