# Generated by Django 6.0 on 2025-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitebranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='site_tagline',
            field=models.CharField(blank=True, help_text='Optional tagline', max_length=255),
        ),
    ]
