# Generated by Django 6.0 on 2025-12-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactpage_donatepage_newspage_program_vacancypage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='ContactUsPage',
        ),
    ]
