# Generated by Django 6.0 on 2025-12-19 01:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_contactpage_contactuspage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('vacancy_title', wagtail.fields.RichTextField(blank=True, help_text='Vancy Title')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Details of the Vacany')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='programimage',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='programimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='vacancypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='information',
            field=wagtail.fields.RichTextField(blank=True, help_text='Infoemation'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction about the organisation'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='what_we_do',
            field=wagtail.fields.RichTextField(blank=True, help_text='List and description of activities'),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_tagline',
            field=models.CharField(blank=True, help_text='Optional tagline', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='International format e.g. +265999000000', max_length=20),
        ),
        migrations.DeleteModel(
            name='DonatePage',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramImage',
        ),
        migrations.DeleteModel(
            name='ProgramPage',
        ),
        migrations.DeleteModel(
            name='VacancyPage',
        ),
    ]
