# Generated by Django 6.0 on 2025-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_donatepage_newspage_program_vacancypage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='vendor_app_url',
            field=models.URLField(blank=True, help_text='Link to the Vendor MIS application'),
        ),
    ]
