# Generated by Django 6.0 on 2025-12-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_partner_homepage_partners'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_title', models.CharField(help_text='Main menu name e.g. About Us, Programs', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Submenu Link',
                'verbose_name_plural': 'Submenu Links',
                'ordering': ['parent_title', 'sort_order'],
            },
        ),
    ]
