# Generated by Django 6.0 on 2025-12-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_submenulink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenulink',
            options={'ordering': ['parent_title', 'sort_order']},
        ),
    ]
