# Generated by Django 5.2.5 on 2026-06-17 14:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_trusteemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='About Us', max_length=255),
        ),
    ]
