# Generated by Django 5.2.5 on 2026-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_homepage_about_text_homepage_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
