# Generated by Django 5.2.5 on 2026-06-25 12:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_aboutpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='values',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
