# Generated by Django 6.0 on 2025-12-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
